### ISSUE TITLE
有个奇怪的问题

### ISSUE THREAD

**Issue by lvZic** [Archmage83/tvapk#5]
tv上安装了小苹果影视后 手机投屏到tv的功能用不了了 苹果手机和安卓机都无法成功投屏到tv上

**Comment by Archmage83** [comment]
这个应该不是app的问题，app没有那么大的权限吧

**Comment by lvZic** [comment]
> 这个应该不是app的问题，app没有那么大的权限吧

我也觉得不单是app的问题 我把电视系统恢复到出厂 投屏功能正常了 
我猜是本地安装的第三方app运行后 改变了tv系统的一些设置参数

**Comment by Archmage83** [comment]
恢复到出厂再次安装小苹果可以吗

**Comment by lvZic** [comment]
> 恢复到出厂再次安装小苹果可以吗

我发现是视频信号的解码方式有问题 要在小苹果中设置解码为软解码 否则就是只有声音没有图像
但很奇怪的是 运行一次小苹果后，所有的官方app 奇异果 芒果TV 腾讯等均只有声音没有图像 且手机投屏tv无法连接
tv恢复出厂后正常 但只要安装并运行一次小苹果后（其他破解app同样）官方app无图像 手机无法投屏

**Comment by Archmage83** [comment]
你是什么电视？我家是小米没出现这种情况

**Comment by lvZic** [comment]
> 你是什么电视？我家是小米没出现这种情况

TCL

**Comment by Archmage83** [comment]
你看看有没有朋友家的电视测试看看

**Comment by lvZic** [comment]
> 你看看有没有朋友家的电视测试看看

算了 也用了好几年了 下次买小米
