### ISSUE TITLE
推荐一个

### ISSUE THREAD

**Issue by jahem** [Archmage83/tvapk#6]
https://github.com/qallen028/eternity
这个是免费的

**Comment by cMing1997** [comment]
> https://github.com/qallen028/eternity 这个是免费的

兄弟，地址没了

**Comment by ITNNTI** [comment]
> https://github.com/qallen028/eternity 这个是免费的

这个也没了

**Comment by jahem** [comment]
> > https://github.com/qallen028/eternity 这个是免费的
> 
> 这个也没了

https://github.com/qallen028/ZyPlayer
